services:

  intranet1:
    build: ./intranet
    container_name: intranet1

  intranet2:
    build: ./intranet
    container_name: intranet2

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - intranet1
      - intranet2
