upstream intranet_servers {
    server intranet1:80;
    server intranet2:80;
}

server {
    listen 80;

    location / {
        proxy_pass http://intranet_servers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
